[supervisord]
redirect_stderr=true
stopsignal=QUIT
autorestart=true
directory=/root

[program:nginx]
priority=10
command=nginx -c /etc/nginx/nginx.conf -g 'daemon off;'

[program:web]
priority=10
directory=/usr/local/lib/web/backend
command=/usr/local/lib/web/backend/run.py
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/1
stderr_logfile_maxbytes=0


[group:x]
programs=sysbus,logind,xvnc,wm,novnc

[program:sysbus]
priority=5
command=/usr/local/bin/system-dbus.sh
stopsignal=KILL

[program:logind]
priority=7
command=/usr/local/bin/system-logind.sh
stopsignal=KILL

[program:wm]
directory=%HOME%
priority=15
command=/usr/local/bin/gnome-session.sh
user=%USER%
stopsignal=TERM
stopwaitsecs=10
environment=DISPLAY=":1",HOME="%HOME%",USER="%USER%",XDG_SESSION_TYPE="x11",XDG_CURRENT_DESKTOP="ubuntu:GNOME",XDG_SESSION_DESKTOP="ubuntu",GNOME_SHELL_SESSION_MODE="ubuntu",GDK_BACKEND="x11",LIBGL_ALWAYS_SOFTWARE="1",MOZ_ENABLE_WAYLAND="0",DBUS_SYSTEM_BUS_ADDRESS="unix:path=/run/dbus/system_bus_socket"

[program:xvnc]
priority=10
command=/usr/local/bin/xvnc.sh
stopsignal=KILL

[program:novnc]
priority=20
directory=/usr/share/novnc
command=/usr/share/novnc/utils/novnc_proxy --listen 6081 --vnc 127.0.0.1:5900
stopasgroup=true
